## NetworkManager.gd
## Owns all ENet peer lifecycle for LAN play.
## Phase 2B: full secret key generation, UDP broadcast, and client discovery.
extends Node


# =========================================================
# CONSTANTS
# =========================================================

## ENet game port. Clients connect here for gameplay traffic.
const PORT:              int   = 7777

## UDP port used for LAN discovery broadcasts.
const DISCOVERY_PORT:    int   = 7778

## Maximum peers excluding the host (host + 3 = 4 players).
const MAX_PEERS:         int   = 3

## Length of the auto-generated session key.
const KEY_LENGTH:        int   = 6

## How often the host re-broadcasts the key, in seconds.
const BROADCAST_INTERVAL: float = 1.0

## How long the client listens for a matching broadcast before giving up.
const DISCOVERY_TIMEOUT: float = 5.0

## Magic prefix prepended to all broadcast packets to avoid collisions
## with unrelated UDP traffic on the same port.
const PACKET_PREFIX:     String = "FF_KEY:"

## Seconds between countdown ticks shown to all peers before game start.
const COUNTDOWN_DURATION: int = 3

# =========================================================
# STATE
# =========================================================

## The session key generated by the host each match. Empty when not hosting.
var session_key: String = ""

## UDP socket used by the host to broadcast the session key.
var _broadcast_socket: PacketPeerUDP = null

## Timer node driving the broadcast interval loop.
var _broadcast_timer: Timer = null


# =========================================================
# SIGNALS
# =========================================================

signal player_connected(peer_id: int)
signal player_disconnected(peer_id: int)
signal connected_to_server()
signal connection_failed()
signal server_disconnected()

## Emitted when key discovery times out with no matching host found.
signal discovery_failed()

## Emitted on all peers each countdown tick. Value counts down from
## COUNTDOWN_DURATION to 1, then the scene changes.
signal countdown_tick(seconds_remaining: int)

# =========================================================
# LIFECYCLE
# =========================================================

func _ready() -> void:
	multiplayer.peer_connected.connect(_on_peer_connected)
	multiplayer.peer_disconnected.connect(_on_peer_disconnected)
	multiplayer.connected_to_server.connect(_on_connected_to_server)
	multiplayer.connection_failed.connect(_on_connection_failed)
	multiplayer.server_disconnected.connect(_on_server_disconnected)


# =========================================================
# PUBLIC API
# =========================================================

## Generates a session key, starts an ENet server, and begins UDP broadcast.
func host_game() -> void:
	var peer := ENetMultiplayerPeer.new()
	var err  := peer.create_server(PORT, MAX_PEERS)

	if err != OK:
		push_error("NetworkManager: Failed to create server on port %d. Error: %s" \
			% [PORT, error_string(err)])
		return

	multiplayer.multiplayer_peer = peer
	GameState.register_player(1)

	session_key = _generate_key()
	print("NetworkManager: Server started. Session key = %s." % session_key)

	_start_udp_broadcast(session_key)


## Discovers the host on LAN by matching [key] via UDP, then connects via ENet.
## Emits discovery_failed if no host is found within DISCOVERY_TIMEOUT seconds.
func join_game(key: String) -> void:
	print("NetworkManager: Searching for host with key '%s'..." % key)
	## Discovery is async — run it as a coroutine and await the result.
	var ip: String = await _discover_host_by_key(key)

	if ip.is_empty():
		push_warning("NetworkManager: Discovery timed out. No host found for key '%s'." % key)
		discovery_failed.emit()
		connection_failed.emit()
		return

	print("NetworkManager: Host found at %s. Connecting..." % ip)
	var peer := ENetMultiplayerPeer.new()
	var err  := peer.create_client(ip, PORT)

	if err != OK:
		push_error("NetworkManager: Failed to create client to %s:%d. Error: %s" \
			% [ip, PORT, error_string(err)])
		connection_failed.emit()
		return

	multiplayer.multiplayer_peer = peer


## Stops broadcasting, disconnects ENet, and resets all session state.
func leave_game() -> void:
	_stop_udp_broadcast()
	if multiplayer.multiplayer_peer:
		multiplayer.multiplayer_peer.close()
	multiplayer.multiplayer_peer = null
	GameState.reset()
	session_key = ""
	print("NetworkManager: Disconnected and session reset.")

## Called by the host when they press Start Game.
## Stops broadcast, runs countdown on all peers, then loads World.tscn.
func start_game() -> void:
	if not multiplayer.is_server():
		push_warning("NetworkManager: start_game() called on a client — ignoring.")
		return
	_stop_udp_broadcast()
	GameState.match_phase = GameState.MatchPhase.IN_GAME
	print("NetworkManager: Starting game — broadcasting countdown.")
	_run_countdown.rpc()

# =========================================================
# SCENE TRANSITION RPC
# =========================================================

## Runs a countdown on all peers, then loads World.tscn.
## Called by the server via RPC — executes on every peer including the server.
@rpc("authority", "call_local", "reliable")
func _run_countdown() -> void:
	for i in range(NetworkManager.COUNTDOWN_DURATION, 0, -1):
		countdown_tick.emit(i)
		await get_tree().create_timer(1.0).timeout
	get_tree().change_scene_to_file("res://scenes/world/World.tscn")

# =========================================================
# UDP BROADCAST (host side)
# =========================================================

## Opens a UDP socket and starts a Timer that re-broadcasts every BROADCAST_INTERVAL.
func _start_udp_broadcast(key: String) -> void:
	_broadcast_socket = PacketPeerUDP.new()

	## set_broadcast_enabled must be called before binding.
	_broadcast_socket.set_broadcast_enabled(true)

	var err := _broadcast_socket.bind(0)  ## bind to any available port
	if err != OK:
		push_error("NetworkManager: Failed to bind broadcast socket. Error: %s" \
			% error_string(err))
		return

	## Create a Timer as a child of this node so it processes automatically.
	_broadcast_timer = Timer.new()
	_broadcast_timer.wait_time   = BROADCAST_INTERVAL
	_broadcast_timer.autostart   = true
	_broadcast_timer.one_shot    = false
	_broadcast_timer.timeout.connect(_send_broadcast.bind(key))
	add_child(_broadcast_timer)

	## Send the first packet immediately without waiting for the first tick.
	_send_broadcast(key)
	print("NetworkManager: UDP broadcast started for key '%s'." % key)


## Sends a single broadcast packet containing the key.
func _send_broadcast(key: String) -> void:
	if _broadcast_socket == null:
		return
	var message  := (PACKET_PREFIX + key).to_utf8_buffer()
	var err      := _broadcast_socket.set_dest_address("255.255.255.255", DISCOVERY_PORT)
	if err != OK:
		push_error("NetworkManager: Failed to set broadcast destination. Error: %s" \
			% error_string(err))
		return
	_broadcast_socket.put_packet(message)


## Stops the broadcast timer and closes the UDP socket.
func _stop_udp_broadcast() -> void:
	if _broadcast_timer:
		_broadcast_timer.stop()
		_broadcast_timer.queue_free()
		_broadcast_timer = null
	if _broadcast_socket:
		_broadcast_socket.close()
		_broadcast_socket = null
	print("NetworkManager: UDP broadcast stopped.")


# =========================================================
# UDP DISCOVERY (client side)
# =========================================================

## Listens on DISCOVERY_PORT for a broadcast packet matching [key].
## Returns the sender IP string on success, or "" on timeout.
## Must be awaited — uses a polling loop with per-frame yields.
func _discover_host_by_key(key: String) -> String:
	var listener := PacketPeerUDP.new()

	## Bind to DISCOVERY_PORT to receive broadcast packets.
	var err := listener.bind(DISCOVERY_PORT)
	if err != OK:
		push_error("NetworkManager: Failed to bind discovery listener on port %d. Error: %s" \
			% [DISCOVERY_PORT, error_string(err)])
		listener.close()
		return ""

	var expected_message := PACKET_PREFIX + key
	var elapsed:  float  = 0.0

	## Poll every frame until a matching packet arrives or the timeout expires.
	while elapsed < DISCOVERY_TIMEOUT:
		## Yield to the engine for one frame and accumulate time.
		await get_tree().process_frame
		elapsed += get_process_delta_time()

		## Drain all packets received this frame.
		while listener.get_available_packet_count() > 0:
			var packet  := listener.get_packet()
			var message := packet.get_string_from_utf8()
			var sender  := listener.get_packet_ip()

			if message == expected_message:
				print("NetworkManager: Matched key '%s' from host at %s." % [key, sender])
				listener.close()
				return sender

	push_warning("NetworkManager: Discovery timed out after %.1f seconds." % DISCOVERY_TIMEOUT)
	listener.close()
	return ""


# =========================================================
# PRIVATE HELPERS
# =========================================================

## Returns a random uppercase alphanumeric string of KEY_LENGTH characters.
func _generate_key() -> String:
	const CHARS := "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
	var key     := ""
	for i in KEY_LENGTH:
		key += CHARS[randi() % CHARS.length()]
	return key


# =========================================================
# MULTIPLAYER SIGNAL HANDLERS
# =========================================================

func _on_peer_connected(peer_id: int) -> void:
	print("NetworkManager: Peer connected — ID %d." % peer_id)
	if multiplayer.is_server():
		GameState.register_player(peer_id)
	player_connected.emit(peer_id)


func _on_peer_disconnected(peer_id: int) -> void:
	print("NetworkManager: Peer disconnected — ID %d." % peer_id)
	if multiplayer.is_server():
		GameState.unregister_player(peer_id)
		if GameState.alive_peers.has(peer_id):
			GameState.eliminate_player(peer_id)
	player_disconnected.emit(peer_id)


func _on_connected_to_server() -> void:
	print("NetworkManager: Connected to server. My peer ID = %d." \
		% multiplayer.get_unique_id())
	connected_to_server.emit()


func _on_connection_failed() -> void:
	push_warning("NetworkManager: Connection failed.")
	multiplayer.multiplayer_peer = null
	connection_failed.emit()


func _on_server_disconnected() -> void:
	push_warning("NetworkManager: Host disconnected.")
	_stop_udp_broadcast()
	multiplayer.multiplayer_peer = null
	GameState.reset()
	server_disconnected.emit()
